In [1]:
from jax import numpy as jnp

/Users/obulpathi/.envs/ai/lib/python3.8/site-packages/jax/_src/lib/__init__.py:34: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "


In [2]:
a = jnp.array([1, 2, 3])
b = jnp.array([4, 5, 6])
c = jnp.array([7, 8, 9])

d = jnp.stack((a, b, c))
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
jnp.array([(1.5, 2, 3), (4, 5, 6)])

DeviceArray([[1.5, 2. , 3. ],
             [4. , 5. , 6. ]], dtype=float32)

In [5]:
jnp.zeros(6)

DeviceArray([0., 0., 0., 0., 0., 0.], dtype=float32)

In [6]:
jnp.ones(6)

DeviceArray([1., 1., 1., 1., 1., 1.], dtype=float32)

In [7]:
a + b

DeviceArray([5, 7, 9], dtype=int32)

In [8]:
c - a

DeviceArray([6, 6, 6], dtype=int32)

In [9]:
10 * jnp.sin(a)

DeviceArray([8.41471 , 9.092974, 1.4112  ], dtype=float32)

In [10]:
A = jnp.array([[1, 1], [0, 1]])
B = jnp.array([[2, 0], [3, 4]])

In [11]:
A * B

DeviceArray([[2, 0],
             [0, 4]], dtype=int32)

In [12]:
A @ B

DeviceArray([[5, 4],
             [3, 4]], dtype=int32)

In [13]:
A.dot(B)

DeviceArray([[5, 4],
             [3, 4]], dtype=int32)

In [14]:
jnp.exp(a)

DeviceArray([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

In [15]:
jnp.sqrt(b)

DeviceArray([2.       , 2.236068 , 2.4494898], dtype=float32)